apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp #name of deployment
  labels:
    app: myapp #name of the label for service assign
spec:
  replicas: 3 # number of pods to replicate
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers: # info about containers
      - name: mypackage
        image: repository/image  
        ports:
        - containerPort: 80



