apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp #name of deployment
  labels:
    app: myapp #name of the label for service assign
spec:
  replicas: 3 # number of pods to replicate
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers: # info about containers
      - name: mypackage
        image: repository/image  
        ports:
        - containerPort: 80
       env:

        -  env:
               - name: SECRET_PASSWORD
                  valueFrom:
                             secretKeyRef:
                                       name: secret-file-with-password
                                       key: password
                                 
       # Define the environment variable
        - name: ENVIRONMENT_VARIABLE_VALUE # Notice that the case is different here
            valueFrom:
             configMapKeyRef:
               name: configmap-example           # The ConfigMap this value comes from.
               key: value-example # The key to fetch. 


